### PR TITLE
Add stdint.h to acebot_compress.c

### PR DESCRIPTION
**Pull request by PinkPandaKatie**
This is needed in order for this file to compile

### CODE REVIEW

**Comment by dghost** [comment]
BTW - This going to need to be wrapped around an #ifdef at some point because Windows (or at least VS)  does not have stdint.h. I'm not too worried about it at the moment since I'm pretty sure the entire `osx` branch of Q2VR as well as the mission pack is broken under VS, but I am going to wind up changing it later.

**Comment by PinkPandaKatie** [comment]
OK, so where is uint32_t defined in Windows? Does it get pulled in by default when you include windows.h?

**Comment by dghost** [comment]
VS only supports ANSI C so it doesn't get any of the explicitly sized types unless you define them yourself. The main project uses a blob of ifdefs that defines them in qcommon.h, iirc, but I haven't figured out what I'm going to do about the game libraries yet since there are many other places where this is going to be an issue.

Like I said, I'm not really worried about it at this moment. The build system is broken under Windows anyways, and I wasn't going to fix it until after I got the Linux build got sorted out again.

**Comment by dghost** [comment]
Not that it's important, but it turns out that Microsoft added stdint.h back into Visual Studio sometime in the last few years and my concerns were over nothing.

_shrug_

**Pull request merged**
